import type { Metadata } from "next";
import "../globals.css";
import { Sider } from "@/components/ui/dashboard/Sider";

export const metadata: Metadata = {
  title: "Swift Realty",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Sider>{children}</Sider>
      </body>
    </html>
  );
}
